# This is the dev docker compose. If you are looking for the deployed one, have a look at deploy/docker-compose.yaml

name: hello-distr-dev

services:
  postgres:
    image: 'postgres:17.4-alpine3.20'
    environment:
      POSTGRES_USER: local
      POSTGRES_PASSWORD: local
      POSTGRES_DB: hello-distr
    volumes:
      - 'postgres:/var/lib/postgresql/data/'
    ports:
      - '5432:5432'

volumes:
  postgres:
