name: hello-distr-dev

services:
  postgres:
    image: 'postgres:17.3-alpine3.20'
    environment:
      POSTGRES_USER: local
      POSTGRES_PASSWORD: local
      POSTGRES_DB: hello-distr
    volumes:
      - 'postgres:/var/lib/postgresql/data/'
    ports:
      - '5432:5432'

volumes:
  postgres:
