name: hello-distr

# tip: only share non-sensitive data to avoid accidental exposure of sensitive values (like passwords) to other containers
x-shared-env: &shared-env
  HELLO_DISTR_HOST: ${HELLO_DISTR_HOST}
  HELLO_DISTR_DB_NAME: ${HELLO_DISTR_DB_NAME}

services:
  postgres:
    image: 'postgres:17.3-alpine3.20'
    environment:
      <<: *shared-env
      POSTGRES_USER: ${HELLO_DISTR_DB_USER:?error}
      POSTGRES_PASSWORD: ${HELLO_DISTR_DB_PASSWORD:?error}
      POSTGRES_DB: ${HELLO_DISTR_DB_NAME:?error}
    volumes:
      - 'postgres:/var/lib/postgresql/data/'
    networks:
      - app_network

  backend:
    image: hello-distr-backend
    environment:
      <<: *shared-env
      DB_URL: postgresql://${HELLO_DISTR_DB_USER:?error}:${HELLO_DISTR_DB_PASSWORD:?error}@postgres/${HELLO_DISTR_DB_NAME:?error}?sslmode=disable
    depends_on:
      - postgres
    networks:
      - app_network

  frontend:
    image: hello-distr-frontend
    environment:
      <<: *shared-env
      NEXT_PUBLIC_API_URL: 'http://${HELLO_DISTR_HOST:?error}/api' # TODO https
    depends_on:
      - backend
    networks:
      - app_network

  proxy:
    image: hello-distr-proxy
    environment:
      <<: *shared-env
      HOST: ${HELLO_DISTR_HOST:?error}
    ports:
      - '80:80' # TODO https
    depends_on:
      - backend
      - frontend
    networks:
      - app_network

volumes:
  postgres:

networks:
  app_network:
    driver: bridge
